[tool.poetry]
name = "google-interview-prep"
version = "0.1.0"
description = "Google Technical Interview Preparation"
authors = ["Jose Miguel Resendiz <josemiguel@ztocker.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.12.8"

[tool.poetry.group.dev.dependencies]
pytest = "^9.0.2"
pytest-cov = "^7.0.0"
ipython = "^9.10.0"
ipdb = "^0.13.13"
ruff = "^0.15.0"
black = "^26.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
